generatorName: cpp-cloudi-service
outputDir: samples/server/petstore/cpp-cloudi-service
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/cpp-cloudi-service
additionalProperties:
  useStructModel: "false"
  addExternalLibs: "true"
